/**
 * Phase 1 source registry — the single source of truth for readiness,
 * authority, collection method, refresh, SLA, degradation, and the exact
 * user promise of every source. Rows implement the Source Readiness Matrix
 * and the exact official allowlist in
 * docs/superpowers/plans/2026-07-23-tradelinks-phase1-foundation.md.
 *
 * Every out-of-scope legacy registry ID is kept here explicitly disabled
 * (`enabled: false`, readiness `UNAVAILABLE`) so "is this source in scope?"
 * is answerable from one place. Validation runs at module load: an enabled
 * source without SLA, cron, or an immutable fixture fails fast.
 */

import { SourceContractSchema, type SourceContract } from "../domain/intelligence/source-contract.js";

type SourceContractInput = Omit<SourceContract, never>;

const GOV_LICENSE = "US Government work (17 U.S.C. §105); public reuse permitted.";
const PLATFORM_LICENSE = "© platform; public page, headline/link fair use.";
const SECONDARY_LICENSE = "© publisher; headline/link fair use.";

const BSR_SELECTORS = {
  item: "#gridItemRoot",
  title: "div[class*='line-clamp']",
  link: "a.a-link-normal[href*='/dp/']",
} as const;

/** Shared contract for the Experimental Amazon public BSR scrapers. */
function bsrSource(
  id: string,
  name: string,
  slug: string,
  refreshCron: string,
  categories: SourceContract["categories"],
  overrides: Partial<SourceContractInput> = {},
): SourceContractInput {
  return {
    id,
    name,
    url: `https://www.amazon.com/gp/bestsellers/${slug}/`,
    market: "US",
    platforms: ["AMAZON"],
    categories,
    authorityLevel: "PLATFORM_OFFICIAL",
    readiness: "EXPERIMENTAL",
    access: "PUBLIC",
    license: PLATFORM_LICENSE,
    fetchMethod: "SCRAPER",
    primaryEvidenceEligible: false,
    freshnessSlaMinutes: 1440,
    refreshCron,
    degradationPolicy: "Hide new demand cards when overdue; policy pages are never affected.",
    userPromise: "Best-seller rank movement observation only; no completeness claim.",
    enabled: true,
    fixture: "amz-bsr.html",
    selectors: { ...BSR_SELECTORS },
    ...overrides,
  };
}

/** Explicitly disabled out-of-scope registry entry (non-US or unsupported). */
function outOfScope(
  id: string,
  name: string,
  url: string,
  authorityLevel: SourceContract["authorityLevel"],
  fetchMethod: SourceContract["fetchMethod"],
  note: string,
): SourceContractInput {
  return {
    id,
    name,
    url,
    market: "US",
    platforms: [],
    categories: ["ALL_PRODUCTS"],
    authorityLevel,
    readiness: "UNAVAILABLE",
    access: "UNAVAILABLE",
    license: "Out of Phase 1 scope; not collected.",
    fetchMethod,
    primaryEvidenceEligible: false,
    freshnessSlaMinutes: null,
    refreshCron: null,
    degradationPolicy: "Disabled for Phase 1; excluded from schedules and user promises.",
    userPromise: "No Phase 1 promise; this source is out of scope.",
    enabled: false,
    fixture: null,
    note,
  };
}

export const PHASE1_SOURCES = SourceContractSchema.array().parse([
  // ---- B. Government official — trade / regulatory ----
  {
    id: "B01",
    name: "USTR Press Releases",
    url: "https://ustr.gov/rss.xml",
    market: "US",
    platforms: [],
    categories: ["ALL_PRODUCTS"],
    authorityLevel: "GOVERNMENT_OFFICIAL",
    readiness: "EXPERIMENTAL",
    access: "PUBLIC",
    license: GOV_LICENSE,
    fetchMethod: "RSS",
    primaryEvidenceEligible: true,
    freshnessSlaMinutes: 1440,
    refreshCron: "0 */12 * * *",
    degradationPolicy: "Mark Stale after 24 hours overdue; preserve item history.",
    userPromise: "US trade-policy context from USTR; not complete customs advice.",
    enabled: true,
    fixture: "b01-ustr.rss.xml",
    note: "Promote to Monitored after fixture and 7-day checks pass.",
  },
  {
    id: "B02",
    name: "US CBP Trade Blog",
    url: "https://www.cbp.gov/rss.xml",
    market: "US",
    platforms: [],
    categories: ["ALL_PRODUCTS"],
    authorityLevel: "GOVERNMENT_OFFICIAL",
    readiness: "EXPERIMENTAL",
    access: "PUBLIC",
    license: GOV_LICENSE,
    fetchMethod: "RSS",
    primaryEvidenceEligible: true,
    freshnessSlaMinutes: 1440,
    refreshCron: "0 */12 * * *",
    degradationPolicy: "Mark Stale after 24 hours overdue.",
    userPromise: "Official CBP announcements; not personalized customs advice.",
    enabled: true,
    fixture: "b02-cbp.rss.xml",
    note: "Promote to Monitored after fixture and 7-day checks pass.",
  },
  {
    id: "B03",
    name: "US Federal Register (Trade/Tariff)",
    url: "https://www.federalregister.gov/api/v1/documents.json?fields[]=title&fields[]=publication_date&fields[]=abstract&fields[]=html_url&per_page=20&order=newest&conditions[term]=import+tariff+antidumping",
    market: "US",
    platforms: [],
    categories: ["ALL_PRODUCTS"],
    authorityLevel: "GOVERNMENT_OFFICIAL",
    readiness: "MONITORED",
    access: "PUBLIC",
    license: GOV_LICENSE,
    fetchMethod: "JSON",
    primaryEvidenceEligible: true,
    freshnessSlaMinutes: 1440,
    refreshCron: "0 */12 * * *",
    degradationPolicy: "Retry on the next cron; mark Stale after 24 hours without a successful check.",
    userPromise: "Federal rule/change coverage for the configured agencies and seller-relevant terms.",
    enabled: true,
    fixture: "b03-federal-register.json",
    note: "Individual reviewed rules can be promoted to Verified.",
  },

  // ---- Official allowlist — safety / consumer protection ----
  {
    id: "US-CPSC-RECALLS",
    name: "CPSC Recalls (REST)",
    url: "https://www.saferproducts.gov/RestWebServices/Recall?format=json",
    market: "US",
    platforms: [],
    categories: ["ALL_PRODUCTS"],
    authorityLevel: "GOVERNMENT_OFFICIAL",
    readiness: "EXPERIMENTAL",
    access: "PUBLIC",
    license: GOV_LICENSE,
    fetchMethod: "JSON",
    primaryEvidenceEligible: true,
    freshnessSlaMinutes: 480,
    refreshCron: "7 */4 * * *",
    degradationPolicy: "REST failure falls back to the official recall RSS (US-CPSC-RSS); mark Stale after 8 hours overdue.",
    userPromise: "Recall notices in covered categories; no legal determination.",
    enabled: false,
    fixture: null,
    note: "Not schedulable until a TS parser + immutable fixture for the SaferProducts REST shape lands.",
  },
  {
    id: "US-CPSC-RSS",
    name: "CPSC Recalls (RSS corroboration)",
    url: "https://www.cpsc.gov/Newsroom/CPSC-RSS-Feed/Recalls-RSS",
    market: "US",
    platforms: [],
    categories: ["ALL_PRODUCTS"],
    authorityLevel: "GOVERNMENT_OFFICIAL",
    readiness: "EXPERIMENTAL",
    access: "PUBLIC",
    license: GOV_LICENSE,
    fetchMethod: "RSS",
    primaryEvidenceEligible: true,
    freshnessSlaMinutes: 480,
    refreshCron: "7 */4 * * *",
    degradationPolicy: "Corroboration feed for US-CPSC-RECALLS; mark Stale after 8 hours overdue.",
    userPromise: "Official CPSC recall notices corroborating the recall REST source.",
    enabled: true,
    fixture: "us-cpsc-rss.xml",
  },
  {
    id: "US-FDA-RECALLS",
    name: "FDA Recalls & Safety Alerts",
    url: "https://www.fda.gov/safety/recalls-market-withdrawals-safety-alerts",
    market: "US",
    platforms: [],
    categories: ["ALL_PRODUCTS"],
    authorityLevel: "GOVERNMENT_OFFICIAL",
    readiness: "EXPERIMENTAL",
    access: "PUBLIC",
    license: GOV_LICENSE,
    fetchMethod: "HTML",
    primaryEvidenceEligible: true,
    freshnessSlaMinutes: 720,
    refreshCron: "11 */6 * * *",
    degradationPolicy: "Suppress any action when the official FDA notice is unavailable; openFDA alone never triggers an action.",
    userPromise: "FDA notices verified against the official page; openFDA is discovery context only.",
    enabled: false,
    fixture: null,
    note: "Monitored only after official-notice reconciliation; parser + fixture land before scheduling.",
  },
  {
    id: "US-FDA-ENFORCEMENT-DISCOVERY",
    name: "openFDA Food Enforcement (discovery)",
    url: "https://api.fda.gov/food/enforcement.json",
    market: "US",
    platforms: [],
    categories: ["FOOD_BEVERAGE"],
    authorityLevel: "GOVERNMENT_OFFICIAL",
    readiness: "EXPERIMENTAL",
    access: "PUBLIC",
    license: GOV_LICENSE,
    fetchMethod: "JSON",
    primaryEvidenceEligible: false,
    freshnessSlaMinutes: 720,
    refreshCron: "13 */6 * * *",
    degradationPolicy: "Discovery context only; never satisfies primary evidence and never triggers an action by itself.",
    userPromise: "Early discovery context for FDA enforcement; always requires official-notice reconciliation.",
    enabled: false,
    fixture: null,
    note: "openFDA warns against using the API alone for public alerts or recall lifecycle tracking.",
  },
  {
    id: "US-FTC-CONSUMER",
    name: "FTC Consumer Protection Press",
    url: "https://www.ftc.gov/feeds/press-release-consumer-protection.xml",
    market: "US",
    platforms: [],
    categories: ["ALL_PRODUCTS"],
    authorityLevel: "GOVERNMENT_OFFICIAL",
    readiness: "EXPERIMENTAL",
    access: "PUBLIC",
    license: GOV_LICENSE,
    fetchMethod: "RSS",
    primaryEvidenceEligible: true,
    freshnessSlaMinutes: 720,
    refreshCron: "17 */6 * * *",
    degradationPolicy: "Mark Stale after 12 hours overdue.",
    userPromise: "Seller-relevant consumer-protection changes selected by review.",
    enabled: true,
    fixture: "us-ftc-consumer.xml",
  },
  {
    id: "US-FTC-ALL",
    name: "FTC Press Releases (all)",
    url: "https://www.ftc.gov/feeds/press-release.xml",
    market: "US",
    platforms: [],
    categories: ["ALL_PRODUCTS"],
    authorityLevel: "GOVERNMENT_OFFICIAL",
    readiness: "EXPERIMENTAL",
    access: "PUBLIC",
    license: GOV_LICENSE,
    fetchMethod: "RSS",
    primaryEvidenceEligible: true,
    freshnessSlaMinutes: 720,
    refreshCron: "19 */6 * * *",
    degradationPolicy: "Mark Stale after 12 hours overdue.",
    userPromise: "Full FTC press-release context; consumer-protection relevance selected by review.",
    enabled: true,
    fixture: "us-ftc-all.xml",
  },
  {
    id: "US-FCC-FR",
    name: "FCC via Federal Register",
    url: "https://www.federalregister.gov/api/v1/documents.json?conditions[agencies][]=federal-communications-commission",
    market: "US",
    platforms: [],
    categories: ["ALL_PRODUCTS"],
    authorityLevel: "GOVERNMENT_OFFICIAL",
    readiness: "EXPERIMENTAL",
    access: "PUBLIC",
    license: GOV_LICENSE,
    fetchMethod: "JSON",
    primaryEvidenceEligible: true,
    freshnessSlaMinutes: 1440,
    refreshCron: "23 */12 * * *",
    degradationPolicy: "No fallback to secondary claims; mark Stale after 24 hours overdue.",
    userPromise: "Configured federal FCC rule coverage via the Federal Register; not all FCC guidance.",
    enabled: true,
    fixture: "us-fcc-fr.json",
  },
  {
    id: "US-FSIS-RECALLS",
    name: "USDA FSIS Recalls",
    url: "https://www.fsis.usda.gov/fsis/api/recall/v/1",
    market: "US",
    platforms: [],
    categories: ["FOOD_BEVERAGE"],
    authorityLevel: "GOVERNMENT_OFFICIAL",
    readiness: "EXPERIMENTAL",
    access: "PUBLIC",
    license: GOV_LICENSE,
    fetchMethod: "JSON",
    primaryEvidenceEligible: true,
    freshnessSlaMinutes: 720,
    refreshCron: "29 */6 * * *",
    degradationPolicy: "Keep the Food & Beverage hub unavailable while this source is Stale.",
    userPromise: "Recall context for the non-launch Food & Beverage category.",
    enabled: false,
    fixture: null,
    note: "Not schedulable until a TS parser + immutable fixture for the FSIS recall REST shape lands.",
  },
  {
    id: "US-APHIS",
    name: "USDA APHIS Announcements",
    url: "https://www.aphis.usda.gov/news/releases",
    market: "US",
    platforms: [],
    categories: ["ALL_PRODUCTS"],
    authorityLevel: "GOVERNMENT_OFFICIAL",
    readiness: "EXPERIMENTAL",
    access: "PUBLIC",
    license: GOV_LICENSE,
    fetchMethod: "HTML",
    primaryEvidenceEligible: true,
    freshnessSlaMinutes: 2880,
    refreshCron: "31 13 * * *",
    degradationPolicy: "Manual review when overdue; no new actions while overdue.",
    userPromise: "Animal/plant health announcement context; no completeness claim.",
    enabled: true,
    fixture: "us-aphis.html",
    selectors: { item: ".views-row", title: "h2, h3, .field-content", link: "a" },
  },

  // ---- Platform official ----
  {
    id: "A02",
    name: "Shopify Changelog",
    url: "https://changelog.shopify.com/feed.xml",
    market: "US",
    platforms: ["SHOPIFY"],
    categories: ["ALL_PRODUCTS"],
    authorityLevel: "PLATFORM_OFFICIAL",
    readiness: "MONITORED",
    access: "PUBLIC",
    license: PLATFORM_LICENSE,
    fetchMethod: "RSS",
    primaryEvidenceEligible: true,
    freshnessSlaMinutes: 480,
    refreshCron: "0 */4 * * *",
    degradationPolicy: "Mark Stale after 8 hours overdue.",
    userPromise: "Official public Shopify changelog items; not every Shopify policy page.",
    enabled: true,
    fixture: "a02-shopify-changelog.xml",
    note: "Reviewed seller changes can be promoted to Verified.",
  },
  {
    id: "AMZ-ANNOUNCEMENTS",
    name: "Amazon Seller Announcements",
    url: "https://sell.amazon.com/blog/announcements",
    market: "US",
    platforms: ["AMAZON"],
    categories: ["ALL_PRODUCTS"],
    authorityLevel: "PLATFORM_OFFICIAL",
    readiness: "MONITORED",
    access: "PUBLIC",
    license: PLATFORM_LICENSE,
    fetchMethod: "HTML",
    primaryEvidenceEligible: true,
    freshnessSlaMinutes: 720,
    refreshCron: "37 */6 * * *",
    degradationPolicy: "Mark Stale after 12 hours overdue; the Amazon Seller Central capability gap stays explicit.",
    userPromise: "Public Amazon announcements only; not complete Seller Central policy coverage.",
    enabled: true,
    fixture: "amz-announcements.html",
    // Brightspot CMS. The two <article> elements on this page are marketing
    // blocks with neither title nor link; the announcements are cards under
    // .PageListD-items-item. Each card holds three anchors — image, category
    // chip ("Announcements") and headline — so the title selector must name
    // the headline specifically or the category chip wins.
    selectors: {
      item: ".PageListD-items-item",
      title: ".PagePromo-title",
      link: ".PagePromo-title a",
      date: ".PagePromo-date",
    },
  },
  {
    id: "AMZ-PRICING-PAGE",
    name: "Amazon Pricing Page (page diff)",
    url: "https://sell.amazon.com/pricing",
    market: "US",
    platforms: ["AMAZON"],
    categories: ["ALL_PRODUCTS"],
    authorityLevel: "PLATFORM_OFFICIAL",
    readiness: "EXPERIMENTAL",
    access: "PUBLIC",
    license: PLATFORM_LICENSE,
    fetchMethod: "PAGE_DIFF",
    primaryEvidenceEligible: false,
    freshnessSlaMinutes: 2880,
    refreshCron: "41 13 * * *",
    degradationPolicy: "Any content-hash change creates an in-review draft; a fetch failure never creates a change.",
    userPromise: "Pricing-page change detection only; no broader policy promise.",
    enabled: true,
    fixture: "amz-pricing-page.html",
  },

  // ---- Secondary context (never primary evidence) ----
  {
    id: "F01",
    name: "Marketplace Pulse",
    url: "https://www.marketplacepulse.com/articles",
    market: "US",
    platforms: ["AMAZON"],
    categories: ["ALL_PRODUCTS"],
    authorityLevel: "REPUTABLE_SECONDARY",
    readiness: "MONITORED",
    access: "PUBLIC",
    license: SECONDARY_LICENSE,
    fetchMethod: "HTML",
    primaryEvidenceEligible: false,
    freshnessSlaMinutes: 720,
    refreshCron: "0 */12 * * *",
    degradationPolicy: "Context only; can never satisfy the Verified primary-evidence invariant.",
    userPromise: "Amazon marketplace discovery and context only.",
    enabled: true,
    fixture: "f01-marketplace-pulse.html",
    selectors: { item: "a[href*='/articles/']", title: "h2, h3, .title" },
  },
  {
    id: "F11",
    name: "EcommerceBytes",
    url: "https://www.ecommercebytes.com/feed/",
    market: "US",
    platforms: ["AMAZON"],
    categories: ["ALL_PRODUCTS"],
    authorityLevel: "REPUTABLE_SECONDARY",
    readiness: "MONITORED",
    access: "PUBLIC",
    license: SECONDARY_LICENSE,
    fetchMethod: "RSS",
    primaryEvidenceEligible: false,
    freshnessSlaMinutes: 720,
    refreshCron: "0 */6 * * *",
    degradationPolicy: "Context only; can never satisfy the Verified primary-evidence invariant.",
    userPromise: "Seller-policy news context; official platform evidence is required for action.",
    enabled: true,
    fixture: "f11-ecommercebytes.xml",
  },
  {
    id: "F02",
    name: "Modern Retail",
    url: "https://www.modernretail.co/feed/",
    market: "US",
    platforms: [],
    categories: ["ALL_PRODUCTS"],
    authorityLevel: "REPUTABLE_SECONDARY",
    readiness: "MONITORED",
    access: "PUBLIC",
    license: SECONDARY_LICENSE,
    fetchMethod: "RSS",
    primaryEvidenceEligible: false,
    freshnessSlaMinutes: 720,
    refreshCron: "0 */4 * * *",
    degradationPolicy: "Context only; cannot satisfy primary evidence.",
    userPromise: "US retail industry discovery and context only.",
    enabled: true,
    fixture: "f02-modernretail.xml",
  },
  {
    id: "F03",
    name: "Retail Dive",
    url: "https://www.retaildive.com/feeds/news/",
    market: "US",
    platforms: [],
    categories: ["ALL_PRODUCTS"],
    authorityLevel: "REPUTABLE_SECONDARY",
    readiness: "MONITORED",
    access: "PUBLIC",
    license: SECONDARY_LICENSE,
    fetchMethod: "RSS",
    primaryEvidenceEligible: false,
    freshnessSlaMinutes: 720,
    refreshCron: "0 */4 * * *",
    degradationPolicy: "Context only; cannot satisfy primary evidence.",
    userPromise: "US retail industry discovery and context only.",
    enabled: true,
    fixture: "f03-retaildive.xml",
  },
  {
    id: "F12",
    name: "Practical Ecommerce",
    url: "https://www.practicalecommerce.com/feed",
    market: "US",
    platforms: [],
    categories: ["ALL_PRODUCTS"],
    authorityLevel: "REPUTABLE_SECONDARY",
    readiness: "MONITORED",
    access: "PUBLIC",
    license: SECONDARY_LICENSE,
    fetchMethod: "RSS",
    primaryEvidenceEligible: false,
    freshnessSlaMinutes: 720,
    refreshCron: "0 */8 * * *",
    degradationPolicy: "Context only; cannot satisfy primary evidence.",
    userPromise: "Ecommerce strategy and analysis context only.",
    enabled: true,
    fixture: "f12-practicalecommerce.xml",
  },
  {
    id: "E01",
    name: "Supply Chain Dive",
    url: "https://www.supplychaindive.com/feeds/news/",
    market: "US",
    platforms: [],
    categories: ["ALL_PRODUCTS"],
    authorityLevel: "REPUTABLE_SECONDARY",
    readiness: "MONITORED",
    access: "PUBLIC",
    license: SECONDARY_LICENSE,
    fetchMethod: "RSS",
    primaryEvidenceEligible: false,
    freshnessSlaMinutes: 720,
    refreshCron: "0 */6 * * *",
    degradationPolicy: "Operational context only; official CBP/USTR evidence is required before any action.",
    userPromise: "Logistics operations context only.",
    enabled: true,
    fixture: "e01-supplychaindive.xml",
  },
  {
    id: "E02",
    name: "FreightWaves",
    url: "https://www.freightwaves.com/news/feed",
    market: "US",
    platforms: [],
    categories: ["ALL_PRODUCTS"],
    authorityLevel: "REPUTABLE_SECONDARY",
    readiness: "MONITORED",
    access: "PUBLIC",
    license: SECONDARY_LICENSE,
    fetchMethod: "RSS",
    primaryEvidenceEligible: false,
    freshnessSlaMinutes: 720,
    refreshCron: "0 */6 * * *",
    degradationPolicy: "Operational context only; official CBP/USTR evidence is required before any action.",
    userPromise: "Freight and customs news context only.",
    enabled: true,
    fixture: "e02-freightwaves.xml",
  },

  // ---- Experimental Amazon public BSR boundaries ----
  bsrSource("D02", "Amazon Best Sellers US (Electronics)", "electronics", "0 */12 * * *", [
    "CONSUMER_ELECTRONICS",
  ]),
  bsrSource("D30", "Amazon Best Sellers US (Home & Garden)", "home-garden", "40 */12 * * *", [
    "HOME_KITCHEN",
  ]),
  bsrSource("D31", "Amazon Best Sellers US (Kitchen)", "kitchen", "48 */12 * * *", [
    "HOME_KITCHEN",
  ]),
  bsrSource("D32", "Amazon Best Sellers US (Toys & Games)", "toys-and-games", "56 */12 * * *", [
    "TOYS_CHILDRENS_PRODUCTS",
  ]),
  bsrSource("D33", "Amazon Best Sellers US (Beauty)", "beauty", "4 */12 * * *", [
    "BEAUTY_PERSONAL_CARE",
  ]),
  bsrSource("D34", "Amazon Best Sellers US (Sports & Outdoors)", "sporting-goods", "12 */12 * * *", [
    "SPORTS_OUTDOORS",
  ]),
  bsrSource("AMZ-BSR-PET-SUPPLIES", "Amazon Best Sellers US (Pet Supplies)", "pet-supplies", "43 */12 * * *", [
    "PET_SUPPLIES",
  ], {
    enabled: false,
    fixture: null,
    note: "Stays disabled until its own fixtures pass (plan: new Pet/Fashion BSR IDs).",
  }),
  bsrSource("AMZ-BSR-FASHION", "Amazon Best Sellers US (Fashion)", "fashion", "47 */12 * * *", [
    "APPAREL_ACCESSORIES",
  ], {
    enabled: false,
    fixture: null,
    note: "Stays disabled until its own fixtures pass (plan: new Pet/Fashion BSR IDs).",
  }),

  // ---- No Phase 1 promise: bot-gated / unproven ----
  {
    id: "D01",
    name: "Google Trends",
    url: "https://trends.google.com/trends/",
    market: "US",
    platforms: [],
    categories: ["ALL_PRODUCTS"],
    authorityLevel: "PLATFORM_OFFICIAL",
    readiness: "UNAVAILABLE",
    access: "UNAVAILABLE",
    license: "Unproven public access; not collected in Phase 1.",
    fetchMethod: "SCRAPER",
    primaryEvidenceEligible: false,
    freshnessSlaMinutes: null,
    refreshCron: null,
    degradationPolicy: "No fallback source; no production schedule.",
    userPromise: "No Phase 1 demand promise.",
    enabled: false,
    fixture: null,
    note: "Unproven public access (matrix); revisit only with an authorized channel.",
  },
  {
    id: "D03",
    name: "Amazon Movers & Shakers US (Electronics)",
    url: "https://www.amazon.com/gp/movers-and-shakers/electronics/",
    market: "US",
    platforms: ["AMAZON"],
    categories: ["CONSUMER_ELECTRONICS"],
    authorityLevel: "PLATFORM_OFFICIAL",
    readiness: "UNAVAILABLE",
    access: "RESTRICTED",
    license: PLATFORM_LICENSE,
    fetchMethod: "SCRAPER",
    primaryEvidenceEligible: false,
    freshnessSlaMinutes: null,
    refreshCron: null,
    degradationPolicy: "No automated fallback or proxy; no production schedule.",
    userPromise: "No Phase 1 promise.",
    enabled: false,
    fixture: null,
    note: "Bot-gated render (verified 2026-06-05); overlaps D02.",
  },

  // ---- Explicitly disabled out-of-scope registry IDs (non-US / unsupported) ----
  outOfScope("B04", "EU Official Journal", "https://eur-lex.europa.eu/rss/rss.xml", "GOVERNMENT_OFFICIAL", "RSS", "Non-US (EU); Phase 1 market is the United States."),
  outOfScope("B05", "EUR-Lex GPSR/REACH", "https://eur-lex.europa.eu/rss/rss.xml", "GOVERNMENT_OFFICIAL", "RSS", "Non-US (EU); Phase 1 market is the United States."),
  outOfScope("B06", "UK Gov customs/VAT", "https://www.gov.uk/search/policy-papers-and-consultations.atom?keywords=customs+vat", "GOVERNMENT_OFFICIAL", "RSS", "Non-US (UK); Phase 1 market is the United States."),
  outOfScope("B07", "German LUCID Packaging Register", "https://www.verpackungsregister.org/en/news", "GOVERNMENT_OFFICIAL", "HTML", "Non-US (DE); Phase 1 market is the United States."),
  outOfScope("B16", "ACCC Product Safety Recalls", "https://www.productsafety.gov.au/rss/recalls.xml", "GOVERNMENT_OFFICIAL", "RSS", "Non-US (AU); Phase 1 market is the United States."),
  outOfScope("D04", "Amazon Best Sellers UK (Electronics)", "https://www.amazon.co.uk/gp/bestsellers/electronics/", "PLATFORM_OFFICIAL", "SCRAPER", "Non-US (UK); Phase 1 platforms are Amazon US and Shopify US."),
  outOfScope("D05", "Amazon Best Sellers UAE (Electronics)", "https://www.amazon.ae/gp/bestsellers/electronics/", "PLATFORM_OFFICIAL", "SCRAPER", "Non-US (UAE); Phase 1 platforms are Amazon US and Shopify US."),
  outOfScope("D06", "Amazon Best Sellers AU (Electronics)", "https://www.amazon.com.au/gp/bestsellers/electronics/", "PLATFORM_OFFICIAL", "SCRAPER", "Non-US (AU); Phase 1 platforms are Amazon US and Shopify US."),
  outOfScope("D07", "TikTok Creative Center", "https://ads.tiktok.com/business/creativecenter/inspiration/popular/pc/en", "PLATFORM_OFFICIAL", "SCRAPER", "Unsupported platform (TikTok) and gated API (verified 2026-06-03)."),
  outOfScope("D11", "Reddit r/FulfillmentByAmazon", "https://www.reddit.com/r/FulfillmentByAmazon.json", "COMMUNITY", "JSON", "Reddit .json returns 403 to datacenter IPs (verified 2026-06-04); community source, not Phase 1 evidence."),
  outOfScope("D12", "Reddit r/AmazonSeller", "https://www.reddit.com/r/AmazonSeller.json", "COMMUNITY", "JSON", "Same Reddit 403 as D11; community source, not Phase 1 evidence."),
  outOfScope("D20", "Mercado Libre — Más Vendidos (MX)", "https://www.mercadolibre.com.mx/mas-vendidos", "PLATFORM_OFFICIAL", "SCRAPER", "Non-US (MX); Phase 1 platforms are Amazon US and Shopify US."),
  outOfScope("D21", "Temu — Best Sellers", "https://www.temu.com/best-sellers.html", "PLATFORM_OFFICIAL", "SCRAPER", "Unsupported platform (Temu); captcha-blocked (verified 2026-06-04)."),
  outOfScope("D22", "Noon — Best Sellers (UAE)", "https://www.noon.com/uae-en/", "PLATFORM_OFFICIAL", "SCRAPER", "Non-US (UAE); unreachable from current env."),
  outOfScope("D23", "AliExpress — Best Selling", "https://www.aliexpress.com/category/best-selling.html", "PLATFORM_OFFICIAL", "SCRAPER", "Unsupported platform (AliExpress); anti-bot blocked (verified 2026-06-04)."),
  outOfScope("D40", "Amazon Best Sellers UK (Home & Garden)", "https://www.amazon.co.uk/gp/bestsellers/home-garden/", "PLATFORM_OFFICIAL", "SCRAPER", "Non-US (UK); Phase 1 platforms are Amazon US and Shopify US."),
  outOfScope("D41", "Amazon Best Sellers UK (Kitchen)", "https://www.amazon.co.uk/gp/bestsellers/kitchen/", "PLATFORM_OFFICIAL", "SCRAPER", "Non-US (UK); Phase 1 platforms are Amazon US and Shopify US."),
  outOfScope("D42", "Amazon Best Sellers UK (Beauty)", "https://www.amazon.co.uk/gp/bestsellers/beauty/", "PLATFORM_OFFICIAL", "SCRAPER", "Non-US (UK); Phase 1 platforms are Amazon US and Shopify US."),
  outOfScope("D50", "Amazon Best Sellers UAE (Kitchen)", "https://www.amazon.ae/gp/bestsellers/kitchen/", "PLATFORM_OFFICIAL", "SCRAPER", "Non-US (UAE); Phase 1 platforms are Amazon US and Shopify US."),
  outOfScope("D51", "Amazon Best Sellers UAE (Beauty)", "https://www.amazon.ae/gp/bestsellers/beauty/", "PLATFORM_OFFICIAL", "SCRAPER", "Non-US (UAE); Phase 1 platforms are Amazon US and Shopify US."),
  outOfScope("D60", "Amazon Best Sellers AU (Kitchen)", "https://www.amazon.com.au/gp/bestsellers/kitchen/", "PLATFORM_OFFICIAL", "SCRAPER", "Non-US (AU); Phase 1 platforms are Amazon US and Shopify US."),
  outOfScope("D61", "Amazon Best Sellers AU (Beauty)", "https://www.amazon.com.au/gp/bestsellers/beauty/", "PLATFORM_OFFICIAL", "SCRAPER", "Non-US (AU); Phase 1 platforms are Amazon US and Shopify US."),
  outOfScope("D62", "Amazon Best Sellers AU (Sports & Outdoors)", "https://www.amazon.com.au/gp/bestsellers/sporting-goods/", "PLATFORM_OFFICIAL", "SCRAPER", "Non-US (AU); Phase 1 platforms are Amazon US and Shopify US."),
  outOfScope("F04", "Tamebay", "https://tamebay.com/feed", "REPUTABLE_SECONDARY", "RSS", "Non-US focus (UK/eBay); Phase 1 market is the United States."),
  outOfScope("F05", "Momentum Works", "https://momentumworks.co/blog/feed/", "REPUTABLE_SECONDARY", "RSS", "Non-US focus (SEA); feed blocked (verified 2026-06-04)."),
  outOfScope("F09", "雨果跨境 CIFNews", "https://www.cifnews.com/xmlconfig/YuGuo.xml", "REPUTABLE_SECONDARY", "RSS", "Non-English CN trade media; feed bot-blocked (verified 2026-06-04)."),
  outOfScope("F10", "亿邦动力 Ebrun", "https://www.ebrun.com/rss", "REPUTABLE_SECONDARY", "RSS", "Non-English CN trade media; rss 403 bot-blocked (verified 2026-06-04)."),
  outOfScope("F13", "SE Asia marketplaces (news)", "https://news.google.com/rss/search?q=(Shopee+OR+Lazada+OR+%22TikTok+Shop%22)+(seller+OR+policy+OR+fees+OR+tax)&hl=en-SG&gl=SG&ceid=SG:en", "REPUTABLE_SECONDARY", "RSS", "Non-US (SEA); Phase 1 market is the United States."),
  outOfScope("F14", "Latin America trade (news)", "https://news.google.com/rss/search?q=(%22Mercado+Libre%22+OR+ecommerce+OR+cross-border)+(Brazil+OR+Mexico+OR+%22Latin+America%22)+(seller+OR+tax+OR+import)&hl=en-US&gl=US&ceid=US:en", "REPUTABLE_SECONDARY", "RSS", "Non-US (LatAm); Phase 1 market is the United States."),
  outOfScope("F15", "Middle East commerce (news)", "https://news.google.com/rss/search?q=(noon+OR+%22Amazon.ae%22+OR+ecommerce)+(UAE+OR+Saudi+OR+%22Middle+East%22)+(seller+OR+VAT+OR+regulation+OR+marketplace)&hl=en-US&gl=US&ceid=US:en", "REPUTABLE_SECONDARY", "RSS", "Non-US (ME); Phase 1 market is the United States."),
  outOfScope("A01", "eBay Seller Updates", "https://www.ebay.com/sellercenter/resources/seller-updates", "PLATFORM_OFFICIAL", "HTML", "Unsupported platform (eBay); Phase 1 platforms are Amazon US and Shopify US."),
  outOfScope("A03", "TikTok Shop US Newsroom", "https://newsroom.tiktok.com/en-us/", "PLATFORM_OFFICIAL", "HTML", "Unsupported platform (TikTok); newsroom is consumer PR, not seller policy (verified 2026-06-05)."),
  outOfScope("A04", "TikTok Shop (news)", "https://news.google.com/rss/search?q=%22TikTok+Shop%22+(seller+OR+policy+OR+commission+OR+fee)&hl=en-US&gl=US&ceid=US:en", "REPUTABLE_SECONDARY", "RSS", "Unsupported platform (TikTok); Phase 1 platforms are Amazon US and Shopify US."),
  outOfScope("X01", "Social — X viral", "https://api.x.com/2/tweets/search/recent", "COMMUNITY", "JSON", "Community social signal; not Phase 1 evidence."),
]);

export const PHASE1_SOURCES_BY_ID = new Map(PHASE1_SOURCES.map((source) => [source.id, source]));
